### ISSUE TITLE
how to install lark_cython on windows

### ISSUE THREAD

**Issue by wqh17101** [lark-parser/lark_cython#2]
**Describe the bug**

install lark_cython on windows

```
  lark_cython.obj : error LNK2001: unresolved external symbol __imp__PyClassMethod_New
  lark_cython.obj : error LNK2001: unresolved external symbol __imp__PyList_Type
  lark_cython.obj : error LNK2001: unresolved external symbol __imp__PyDict_GetItemString
...
```

**To Reproduce**

pip install lark-cython

What do i need to install if i want to install on Windows

**Comment by Erotemic** [comment]
@wqh17101 I've built a set of wheels for lark-cython. Do you want to try downloading, unzipping, and then attempting to pip install the appropriate one? 

https://github.com/lark-parser/lark_cython/suites/7481642149/artifacts/306892242

These will likely be on pypi soon, but any verification that they work would be helpful.

**Comment by wqh17101** [comment]
I simplely tested it on my win11, it works. I will test next week for more real cases.

**Comment by wqh17101** [comment]
Thank you for your enhancement.
