### ISSUE TITLE
Resolve differences from Lark

### ISSUE THREAD

**Issue by wqh17101** [lark-parser/lark_cython#6]
**Suggestion**

I mentioned the differences from Lark, is there any way to resolve?
**Describe alternatives you've considered**
Deploy from lark without any changes

**Comment by erezsh** [comment]
Can you be more specific?

Anything that works with lark_cython will also work with Lark.

**Comment by wqh17101** [comment]
@erezsh  Token instances do not inherit from str. You must use the value attribute to get the string. This one

**Comment by erezsh** [comment]
Yes, I don't know of a way to solve it, while maintaining performance.

I suggest you always use `.value` in both lark-cython and Lark.

Or, write a transformer that converts `lark-cython.Token` to `lark.Token`, but of course at the cost of performance.

**Comment by wqh17101** [comment]
All right , i will try.
