### ISSUE TITLE
Setting non-string values on Tokens

### ISSUE THREAD

**Issue by geographika** [lark-parser/lark_cython#7]
Token values in lark_cython are [typed as str](https://github.com/lark-parser/lark_cython/blob/503b13de4afdf2954d741cd0dc726216ae27731e/lark_cython/lark_cython.pyx#L20). 

In [my Transformer ](https://github.com/geographika/mappyfile/blob/4f2234319bd1c6f4cba572f744673441adf0569b/mappyfile/transformer.py#L566-L569)I'm changing the token values to their correct types, for example `int`:

```python
    def int(self, t):
        v = t[0]
        v.value = int(v.value)
        # return full Token rather than an int as Token properties are required later
        return v
```

This throws the following error in lark_cython:

```
lark_cython\lark_cython.pyx:20: in lark_cython.lark_cython.Token.value.__set__  TypeError: Expected unicode, got int
```

I return the full token in the transformer, rather than simply an `int` value, as [later logic ](https://github.com/geographika/mappyfile/blob/4f2234319bd1c6f4cba572f744673441adf0569b/mappyfile/transformer.py#L126)(for error handling etc.) takes advantage of the token properties:

```python
line, column = key_token.line, key_token.column
```

Do token values have to be strings in lark_cython?
If so, is there any approach which would allow token values to be converted to support `int`, `float` etc.?

**Comment by geographika** [comment]
Thanks @erezsh, and thanks for this project!
This approach works fine for all the transformer functions that convert to any types that aren't `str`. 
Does this approach however negate any performance boosts from using `lark_cython`? The full test suite went from 1min20 to 1min50 (a very rough benchmark). 
I'll continue to play around and look at failing tests.

**Comment by erezsh** [comment]
This shouldn't have any direct effect on lark-cython's performance. But it's possible that you are creating a lot of Token instances, and that's taking a lot of time. (I do remember mappyfiles having a lot of ints in them)
