### ISSUE TITLE
Meta is always empty while using cython lark

### ISSUE THREAD

**Issue by ernestoarbitrio** [lark-parser/lark_cython#9]
This is my parser:

```python3
    lark_kwargs = {
        "parser": "lalr",
        "lexer": "contextual",
        "propagate_positions": True,
        "_plugins": lark_cython.plugins,
    }
    lang_parser = Lark(lang_def, start="start", **lark_kwargs)
```
I'd like to propagate the line positions, without cython-lark it works fine, but once i enable the plugins the meta value is always empty.

Do you have any suggestion on what's wrong ?

**Comment by erezsh** [comment]
Bug confirmed.

This is happening because lark-cython still uses Lark's parse-tree-builder, which in turn uses `isinstance(..., Token)`, which only matches Lark Tokens, instead of lark-cython Tokens.

See this line: https://github.com/lark-parser/lark/blob/master/lark/parse_tree_builder.py#L74

**Comment by erezsh** [comment]
The following change works:

```
            elif hasattr(c, 'line'): #isinstance(c, Token):
                return c
```
But that would break backwards compatibility. 

And unfortunately lark-cython cannot inherit from `lark.Token`.

So I'm not sure what's the best way to solve this. Another option is to update lark-cython to use its own parse-tree-builder.

**Comment by erezsh** [comment]
Right now lark-cython uses Lark's regular ParseTreeBuilder class. If that class is copied and adapted into lark-cython, that won't be a problem anymore. (and if done correctly, should be a little faster too)

**Comment by ernestoarbitrio** [comment]
oh gotcha ... do you wanna me try to do this?

**Comment by ernestoarbitrio** [comment]
yes I do not have enough experience on lark. Even the last solution probably requires more knowledge. I would be happy to help but I think I need help as well :D

**Comment by erezsh** [comment]
Okay, so I just created a PR for Lark, have a look: https://github.com/lark-parser/lark/pull/1203

With this change, all you need is to add this to lark_cython.Token

```python
    def __lark_meta__(self):
        return self
```

And for Tree return `self.meta`.

Then add some tests to lark-cython, and that's it. Makes sense?

**Comment by ernestoarbitrio** [comment]
> Okay, so I just created a PR for Lark, have a look: [lark-parser/lark#1203](https://github.com/lark-parser/lark/pull/1203)
> 
> With this change, all you need is to add this to lark_cython.Token
> 
> ```python
>     def __lark_meta__(self):
>         return self
> ```
> 
> And for Tree return `self.meta`.
> 
> Then add some tests to lark-cython, and that's it. Makes sense?

yes I'll try. thx
